project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - href: https://umairdurrani.com/
        text: About
format:
  html:
    theme: united
    css: styles.css
    df-print: paged
    
freeze: true



